config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  get 'terms', to: 'home#terms'

  resources :matches, only: [:index, :show] do
    collection do
      get 'ended'
    end

    member do
      resources :hints, as: :match_hint, only: :new
    end
  end

  resources :hints, only: [:index, :show, :create]

  resources :users, only: [:show] do
    collection do
      get 'dashboard'
      get 'ranking'
    end
  end

  resources :contacts, only: [:index, :show, :new, :create] do
    collection do
      post 'answer_message'
    end

    member do
      get 'answer'
    end
  end

  resources :moviments, only: [:index, :create]
end

app/models/hint.rb
# frozen_string_literal: true

class Hint < ApplicationRecord
  belongs_to :user
  belongs_to :match

  scope :by_user, ->(user) { where(user: user).order(:created_at) }

  TYPES = {
    yellow_cards: {
      hint: {
        mandatory: ->(hint) { hint.mandatory_yellow_cards },
        visitor: ->(hint) { hint.visitor_yellow_cards }
      },
      match: {
        mandatory: ->(hint) { hint.match_mandatory_yellow_cards },
        visitor: ->(hint) { hint.match_visitor_yellow_cards }
      }
    },
    fouls: {
      hint: {
        mandatory: ->(hint) { hint.mandatory_fouls },
        visitor: ->(hint) { hint.visitor_fouls }
      },
      match: {
        mandatory: ->(hint) { hint.match_mandatory_fouls },
        visitor: ->(hint) { hint.match_visitor_fouls }
      }
    }
  }.freeze

  delegate :mandatory_name,
           :visitor_name,
           :match_date,
           :league_name, to: :match

  delegate :mandatory_goals_first_period,
           :mandatory_goals_last_period,
           :mandatory_yellow_cards,
           :mandatory_fouls,
           :visitor_goals_first_period,
           :visitor_goals_last_period,
           :visitor_yellow_cards,
           :visitor_fouls,
           :mandatory_goals,
           :visitor_goals,
           :winner,
           :finished?, to: :match, prefix: true

  def mandatory_goals
    mandatory_goals_first_period + mandatory_goals_last_period
  end

  def visitor_goals
    visitor_goals_first_period + visitor_goals_last_period
  end

  def winner
    HintsServices::Winner.retrieve(self)
  end

  def hint_type_team(type, team)
    TYPES[type][:hint][team].call(self)
  end

  def match_type_team(type, team)
    TYPES[type][:match][team].call(self)
  end
end

app/controllers/hints_controller.rb
# frozen_string_literal: true

class HintsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_match, only: :create

  def index
    @hints = Hint.by_user(current_user).page(params[:page] || 0)
  end

  def show
    @hint = Hint.find_by(id: params_id, user: current_user)
  end

  def new
    @match = Match.find(params_id)
  end

  def create
    HintsServices::Creator.execute(params: hint_params, match: @match, user: current_user)
    redirect_to hints_path
  end

  private

  def hint_params
    params.require(:hint).permit(:mandatory_goals_first_period,
                                 :visitor_goals_first_period,
                                 :mandatory_goals_last_period,
                                 :visitor_goals_last_period,
                                 :mandatory_yellow_cards,
                                 :visitor_yellow_cards,
                                 :mandatory_fouls,
                                 :visitor_fouls)
  end

  def set_match
    @match = Match.find(params[:match_id])
  end
end

app/views/hints/partials/_list.html.erb
<tr>
  <td><span><%= hint.mandatory_name %></span><span>VS</span><span><%= hint.visitor_name %></span></td>
  <td><%= hint.match_date.strftime("%d/%m/%Y") %></td>
  <td><%= link_to t('see_hint'), hint_path(hint), title: t('see_hint') %></td>
</tr>

app/views/hints/partials/_mandatory_result.html.erb
<ul>
  <li> <div> <%= t(:goals_first_period) %> <span><%= number_field(:hint, :mandatory_goals_first_period, in: 0..99, value: '0', step: 1, class: 'mandatory-goals') %></span> </div> </li>
  <li> <div> <%= t(:goals_last_period) %> <span><%= number_field(:hint, :mandatory_goals_last_period, in: 0..99, value: '0', step: 1, class: 'mandatory-goals') %></span> </div> </li>
  <li> <div> <%= t(:yellow_cards) %> <span><%= number_field(:hint, :mandatory_yellow_cards, in: 0..99, value: '0', step: 1) %></span> </div> </li>
  <li> <div> <%= t(:fouls) %> <span><%= number_field(:hint, :mandatory_fouls, in: 0..99, value: '0', step: 1) %></span> </div> </li>
</ul>

app/views/hints/partials/_match_not_finished.html.erb
<div class="col-md-12">
  <span class="thbg-colortwo box"><%= t('hints.show.points_not_calculated') %></span>
</div>

app/views/hints/partials/_points.html.erb
<div class="col-md-12">
  <!-- Mostrar pontos do usuário na partida (Fazer calculo Após a partida ser computada) -->
  <span class="thbg-colortwo box"><%= t('hints.show.points', points: hint.points) %></span>
</div>

app/views/hints/partials/_visitor_result.html.erb
<ul>
  <li> <div> <%= t(:goals_first_period) %> <span><%= number_field(:hint, :visitor_goals_first_period, in: 0..99, value: '0', step: 1, class: 'visitor-goals') %></span> </div> </li>
  <li> <div> <%= t(:goals_last_period) %> <span><%= number_field(:hint, :visitor_goals_last_period, in: 0..99, value: '0', step: 1, class: 'visitor-goals') %></span> </div> </li>
  <li> <div> <%= t(:yellow_cards) %> <span><%= number_field(:hint, :visitor_yellow_cards, in: 0..99, value: '0', step: 1) %></span> </div> </li>
  <li> <div> <%= t(:fouls) %> <span><%= number_field(:hint, :visitor_fouls, in: 0..99, value: '0', step: 1) %></span> </div> </li>
</ul>