config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  get 'terms', to: 'home#terms'

  resources :matches, only: [:index, :show] do
    collection do
      get 'ended'
    end

    member do
      resources :hints, as: :match_hint, only: :new
    end
  end

  resources :hints, only: [:index, :show, :create]

  resources :users, only: [:show] do
    collection do
      get 'dashboard'
      get 'ranking'
    end
  end

  resources :contacts, only: [:index, :show, :new, :create] do
    collection do
      post 'answer_message'
    end

    member do
      get 'answer'
    end
  end

  resources :moviments, only: [:index, :create]
end

app/views/shared/template/_banner.html.erb
<div id="banner" class="background-color">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <ins class="adsbygoogle"
      style="display:block"
      data-ad-client="ca-pub-9728153179593956"
      data-ad-slot="1367020430"
      data-ad-format="auto"
      data-full-width-responsive="true"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/shared/template/_footer.html.erb
<footer class="footer-bottom-2" id="footer">
    <div class="footer-medium">
        <div class="item divider-item"></div>
        <div class="container">
            <div class="row">
                <div id="text-2" class="col-md-4 widget widget_text widget">
                    <h3 class="widget-title"><%= t('footer.contact_social') %></h3>
                    <ul class="social-links small">
                            <li class="tw-bg"><a target="_self" href="#"><span class="icon icon-twitter"></a></li>
                            <li class="fb-bg"><a target="_self" href="#"><span class="icon icon-facebook"></span></a></li>
                            <li class="youtube-bg"><a target="_self" href="#"><span class="icon icon-youtube"></a></li>
                            <li class="linkedin-bg"><a target="_self" href="#"><span class="icon icon-instagram"></a></li>
                        </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="bottom-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>©2018 Chute Feito. All Right Reserved</p>
            </div>
        </div>
    </div>
</div>

app/views/shared/template/_header.html.erb
<header id="mainheader" class="header-absolute header-1">
    <div class="topbar-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-6 kode_bg_white">
                    <div class="bx-wrapper" style="max-width: 100%;">
                        <div class="bx-viewport">
                        <!--
                            <ul class="bxslider">
                                <li><span class="barinfo"><strong>Latest News : </strong></span></li>
                            </ul>
                        -->
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="userinfo">
                        <% unless user_signed_in? %>
                        <li><%= link_to t('header.login'), new_user_session_path, title: t('header.login') %></li>
                        <li><%= link_to t('header.register'), new_user_registration_path, title: t('header.register') %></li>
                        <% else %>
                        <li><%= link_to t('header.dashboard'), dashboard_users_path, title: t('header.dashboard') %></li>
                        <li><%= link_to t(:extract), moviments_path, title: t(:extract) %></li>
                        <li><%= link_to t('header.hints'), hints_path, title: t('header.hints') %></li>
                        <li><%= link_to t('header.messages'), contacts_path, title: t('header.messages') %></li>
                        <li><%= link_to t('header.logout'), destroy_user_session_path, method: :delete, title: t('header.logout') %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="header-8">
        <div class="container">
            <div id="dl-menu" class="dl-menuwrapper">
                <button class="dl-trigger"><%= t('header.menu.open_menu') %></button>
                <ul class="dl-menu">
                    <li>
                        <%= link_to t('header.menu.home'), root_path, title: t('header.menu.home') %>
                    </li>
                    <li><%= link_to t('header.menu.about_us'), terms_path, title: t('header.menu.about_us') %></li>
                    <li>
                        <%= link_to t('text_matches'), 'javascript:void(0)', title: t('text_matches') %>
                        <ul class="dl-submenu">
                            <li class="menu-item"><%= link_to t('header.menu.next_matches'), matches_path, title: t('header.menu.next_matches') %></li>
                            <li class="menu-item"><%= link_to t('header.menu.ended_matches'), ended_matches_path, title: t('header.menu.ended_matches') %></li>
                        </ul>
                    </li>
                    <li> <%= link_to t('header.menu.ranking'), ranking_users_path, title: t('header.menu.ranking') %> </li>
                    <li>
                        <a href="#" title="<%= t('header.menu.faq') %>"><%= t('header.menu.faq') %></a>
                    </li>
                    <li><%= link_to t('header.menu.contact'), new_contact_path, title: t('header.menu.contact') %></li>
                </ul>
            </div>
            <div class="navigation pull-left">
                <div class="navigation-wrapper">
                    <nav class="navigation">
                        <div>
                            <ul class="menu">
                                <li><%= link_to t('header.menu.home'), root_path, title: t('header.menu.home') %></li>
                                <li><%= link_to t('header.menu.about_us'), terms_path, title: t('header.menu.about_us') %></li>
                                <li>
                                    <%= link_to t('text_matches'), 'javascript:void(0)', title: t('text_matches') %>
                                    <ul class="dl-submenu">
                                        <li class="menu-item"><%= link_to t('header.menu.next_matches'), matches_path, title: t('header.menu.next_matches') %></li>
                                        <li class="menu-item"><%= link_to t('header.menu.ended_matches'), ended_matches_path, title: t('header.menu.ended_matches') %></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <div class="clear"></div>
                </div>
            </div>


            <div class="logo">
                <%= link_to image_tag("logo.png", alt: "", title: "Facebook Login"), root_path %>
            </div>


            <div class="navigation">
                <div class="navigation-wrapper">
                    <nav class="navigation">
                        <div class="menu-menu-2-container">
                            <ul class="menu">
                                <li><%= link_to t('header.menu.ranking'), ranking_users_path, title: t('header.menu.ranking') %></li>
                                <li><a href="#" title="<%= t('header.menu.faq') %>"><%= t('header.menu.faq') %></a></li>
                                <li><%= link_to t('header.menu.contact'), new_contact_path, title: t('header.menu.contact') %></li>
                            </ul>
                        </div>
                    </nav>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</header>